"""empty message

Revision ID: 0eb0f1ab3843
Revises: 43c870406583
Create Date: 2023-07-29 21:49:51.927834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb0f1ab3843'
down_revision = '43c870406583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passResetToken', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passResetTokenExp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passResetTokenExp')
    op.drop_column('users', 'passResetToken')
    # ### end Alembic commands ###
