"""empty message

Revision ID: 11655f4eda13
Revises: f5e4e61e0da2
Create Date: 2023-07-31 16:28:09.405792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11655f4eda13'
down_revision = 'f5e4e61e0da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
