"""empty message

Revision ID: 18915931b1a1
Revises: de5958acc48f
Create Date: 2023-07-29 12:00:38.204644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18915931b1a1'
down_revision = 'de5958acc48f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'products', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    # ### end Alembic commands ###
