"""empty message

Revision ID: 193ba82f64ab
Revises: c552ffd7d1aa
Create Date: 2023-07-28 22:11:38.944529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193ba82f64ab'
down_revision = 'c552ffd7d1aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
