"""empty message

Revision ID: 1a038a2babb3
Revises: fe24af1d56b3
Create Date: 2023-10-20 22:40:31.643406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a038a2babb3'
down_revision = 'fe24af1d56b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'createdAt')
    op.add_column('orders', sa.Column('addressLine1', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('addressLine2', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('postalCode', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('country', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('state', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('mobile', sa.String(), nullable=False))
    op.alter_column('orders', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('orders', 'mobile')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'postalCode')
    op.drop_column('orders', 'addressLine2')
    op.drop_column('orders', 'addressLine1')
    op.add_column('order_items', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
