"""empty message

Revision ID: 20248e03a172
Revises: abc1331f8b2f
Create Date: 2023-07-31 16:42:38.695769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20248e03a172'
down_revision = 'abc1331f8b2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_categoryId_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'blog_categories', ['categoryId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_categoryId_fkey', 'blogs', 'product_categories', ['categoryId'], ['id'])
    # ### end Alembic commands ###
