"""empty message

Revision ID: 24af6c6f3ab0
Revises: c9e4b46f1d80
Create Date: 2023-08-03 01:39:09.659180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24af6c6f3ab0'
down_revision = 'c9e4b46f1d80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coupons', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='unique')
    # ### end Alembic commands ###
