"""empty message

Revision ID: 2f8ddf52557a
Revises: 88203dadc978
Create Date: 2023-07-28 22:54:42.204188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8ddf52557a'
down_revision = '88203dadc978'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked')
    # ### end Alembic commands ###
