"""empty message

Revision ID: 471e114e8ef3
Revises: b749bb6d9bbb
Create Date: 2023-10-06 15:59:37.029797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '471e114e8ef3'
down_revision = 'b749bb6d9bbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('ratings', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.drop_column('ratings', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('ratings', 'updatedAt')
    op.drop_column('ratings', 'createdAt')
    # ### end Alembic commands ###
