"""empty message

Revision ID: 473a5a16eed6
Revises: f3b64530c15b
Create Date: 2023-08-04 02:15:25.133852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473a5a16eed6'
down_revision = 'f3b64530c15b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'discount')
    # ### end Alembic commands ###
