"""empty message

Revision ID: 636756eb5746
Revises: 54982ea66b46
Create Date: 2023-07-31 16:12:07.075275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636756eb5746'
down_revision = '54982ea66b46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('categoryId', sa.Integer(), nullable=True))
    op.drop_constraint('products_category_key', 'products', type_='unique')
    op.create_foreign_key(None, 'products', 'product_categories', ['categoryId'], ['id'])
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_unique_constraint('products_category_key', 'products', ['category'])
    op.drop_column('products', 'categoryId')
    # ### end Alembic commands ###
