"""empty message

Revision ID: 68c609d0d764
Revises: 69b29bbe4861
Create Date: 2023-08-03 14:41:06.669207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c609d0d764'
down_revision = '69b29bbe4861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'createdAt')
    # ### end Alembic commands ###
