"""empty message

Revision ID: 6e438e30a647
Revises: 3edc37a086bb
Create Date: 2023-08-03 15:40:19.455547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e438e30a647'
down_revision = '3edc37a086bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
