"""empty message

Revision ID: 81d9c1cee224
Revises: 473a5a16eed6
Create Date: 2023-08-04 02:38:51.292887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d9c1cee224'
down_revision = '473a5a16eed6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('couponId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'coupons', ['couponId'], ['id'])
    op.drop_column('cart_items', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'couponId')
    # ### end Alembic commands ###
