"""empty message

Revision ID: 83c2ed9f3d5d
Revises: 2f8ddf52557a
Create Date: 2023-07-28 23:59:13.695039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c2ed9f3d5d'
down_revision = '2f8ddf52557a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refreshToken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refreshToken')
    # ### end Alembic commands ###
