"""empty message

Revision ID: 84ce4121003f
Revises: 7390ea66a328
Create Date: 2023-07-30 15:36:09.216278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ce4121003f'
down_revision = '7390ea66a328'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
