"""empty message

Revision ID: 8be726b9fa2f
Revises: 84ce4121003f
Create Date: 2023-07-30 16:14:10.123713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be726b9fa2f'
down_revision = '84ce4121003f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'isDisliked')
    op.drop_column('blogs', 'isLiked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('isLiked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('isDisliked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
