"""empty message

Revision ID: 8c0e376cfe7d
Revises: 471e114e8ef3
Create Date: 2023-10-15 20:38:21.384400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0e376cfe7d'
down_revision = '471e114e8ef3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
