"""empty message

Revision ID: 8e9238e07c18
Revises: 00cfb069d480
Create Date: 2023-08-15 00:47:40.742862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9238e07c18'
down_revision = '00cfb069d480'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_images_publicId_key', 'blog_images', type_='unique')
    op.drop_constraint('product_images_publicId_key', 'product_images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_images_publicId_key', 'product_images', ['publicId'])
    op.create_unique_constraint('blog_images_publicId_key', 'blog_images', ['publicId'])
    # ### end Alembic commands ###
