"""empty message

Revision ID: 9968bf5738dc
Revises: f0df74f538d4
Create Date: 2023-08-03 23:44:10.710247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9968bf5738dc'
down_revision = 'f0df74f538d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    op.drop_column('cart_items', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cart_items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
