"""empty message

Revision ID: a71eca7452ab
Revises: ab4416f92602
Create Date: 2023-07-30 20:37:12.297728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71eca7452ab'
down_revision = 'ab4416f92602'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'products', ['brand'])
    op.create_unique_constraint(None, 'products', ['color'])
    op.create_unique_constraint(None, 'products', ['category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    # ### end Alembic commands ###
