"""empty message

Revision ID: abc1331f8b2f
Revises: bac69f46e932
Create Date: 2023-07-31 16:41:40.577200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc1331f8b2f'
down_revision = 'bac69f46e932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('categoryId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'product_categories', ['categoryId'], ['id'])
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'categoryId')
    # ### end Alembic commands ###
