"""empty message

Revision ID: b2cdbf3b3f60
Revises: e6dd221ee7d0
Create Date: 2023-08-16 21:42:13.283725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cdbf3b3f60'
down_revision = 'e6dd221ee7d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'image')
    # ### end Alembic commands ###
