"""empty message

Revision ID: bac69f46e932
Revises: 11655f4eda13
Create Date: 2023-07-31 16:33:56.716053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac69f46e932'
down_revision = '11655f4eda13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_brand_key', 'products', type_='unique')
    op.drop_constraint('products_color_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_color_key', 'products', ['color'])
    op.create_unique_constraint('products_brand_key', 'products', ['brand'])
    # ### end Alembic commands ###
