"""empty message

Revision ID: c83eb0ba2e28
Revises: d0754376f105
Create Date: 2023-08-02 23:49:12.966737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83eb0ba2e28'
down_revision = 'd0754376f105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'created')
    # ### end Alembic commands ###
