"""empty message

Revision ID: ca25a21af3f5
Revises: 24af6c6f3ab0
Create Date: 2023-08-03 14:36:26.973161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca25a21af3f5'
down_revision = '24af6c6f3ab0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
