"""empty message

Revision ID: de8ea09bc324
Revises: c83eb0ba2e28
Create Date: 2023-08-03 00:17:13.896933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8ea09bc324'
down_revision = 'c83eb0ba2e28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'comment')
    # ### end Alembic commands ###
