"""empty message

Revision ID: e23601b75714
Revises: eb1d847f234a
Create Date: 2023-07-31 19:45:36.704905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23601b75714'
down_revision = 'eb1d847f234a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('likes', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'createdAt')
    op.drop_column('dislikes', 'createdAt')
    # ### end Alembic commands ###
