"""empty message

Revision ID: e6dd221ee7d0
Revises: 8e9238e07c18
Create Date: 2023-08-16 21:25:03.666145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dd221ee7d0'
down_revision = '8e9238e07c18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_categories', 'image')
    # ### end Alembic commands ###
