"""empty message

Revision ID: eb1d847f234a
Revises: 6a8454878747
Create Date: 2023-07-31 18:15:16.170931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1d847f234a'
down_revision = '6a8454878747'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brandId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brandId'], ['id'])
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'brandId')
    # ### end Alembic commands ###
