"""empty message

Revision ID: f0df74f538d4
Revises: b602a0f6a901
Create Date: 2023-08-03 23:16:21.766672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0df74f538d4'
down_revision = 'b602a0f6a901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
