"""empty message

Revision ID: f5e4e61e0da2
Revises: 636756eb5746
Create Date: 2023-07-31 16:14:20.326951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e4e61e0da2'
down_revision = '636756eb5746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
